name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: windows-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe' '.\CustomerDB.VS\CustomerDB.VS.sqlproj' /p:Configuration=Release

    - name: Upload dacpac
      uses: actions/upload-artifact@v3
      with:
        name: DACPAC
        path: ${{ github.workspace }}\Customer.Database\bin\Release\CustomerDB.VS.dacpac
